### ISSUE TITLE
printer offline

### ISSUE THREAD

**Issue by spectron2077** [Raise3D/Octoprint-Raisecloud#7]
printer deosent show up

**Comment by Riku-lu** [comment]
> printer deosent show up
Hi,
this is Riku from RaiseCloud team , could you please refer to attached file to reinstall plug-in of RaiseCloud. if the printer is still offline, please send log file to my email(xiaoping.lu@raise3d.com). thank you! 
[reinstall plugin & download log.docx](https://github.com/Raise3D/Octoprint-Raisecloud/files/5651492/reinstall.plugin.download.log.docx)

**Comment by spectron2077** [comment]
I've tried that but raisecloud only works intermittently

**Comment by Riku-lu** [comment]
is it sometimes  Offline, sometimes Standby ? can you provide us more information about issue? please send me your RaiseCloud account, printer name and  the log file you can download log file according to document I sent you yesterday, as these info can help us to find the root cause of issue. thank you!

**Comment by spectron2077** [comment]
I fixed it by updating octoprint
